# Generated by Django 5.1.5 on 2025-02-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rango", "0003_page_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="likes",
        ),
        migrations.AddField(
            model_name="category",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
